"""Schemas module for Meeting Notes API."""
from meeting_notes_agent.schemas.auth import (
    UserRegister,
    UserLogin,
    TokenResponse,
    RefreshTokenRequest,
    ChangePasswordRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    VerifyEmailRequest,
)
from meeting_notes_agent.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserUpdateSelf,
    UserResponse,
    UserAdminResponse,
    UserProfileResponse,
    UserQuotaResponse,
    UserQuotaUpdate,
    UserCreditsResponse,
    UserCreditsAdjust,
    UserUsageResponse,
)
from meeting_notes_agent.schemas.meeting import (
    AttendeeBase,
    AttendeeResponse,
    MeetingBase,
    MeetingCreate,
    MeetingUpdate,
    MeetingListItem,
    MeetingResponse,
    MeetingStatusResponse,
    MeetingResultResponse,
    AudioUploadResponse,
    TranscriptUploadResponse,
    ProcessingStartResponse,
    ReviewContentResponse,
    ReviewRequest,
    ReviewResponse,
    EmailDraftResponse,
    EmailReviewRequest,
    EmailSendResponse,
)
from meeting_notes_agent.schemas.task import (
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskListResponse,
)
from meeting_notes_agent.schemas.admin import (
    AdminStatsResponse,
    AdminUserListItem,
    AdminUserDetail,
    AdminUserUpdate,
    AdminMeetingListItem,
    AdminMeetingStatusResponse,
)

__all__ = [
    # Auth
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "RefreshTokenRequest",
    "ChangePasswordRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "VerifyEmailRequest",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserUpdateSelf",
    "UserResponse",
    "UserAdminResponse",
    "UserProfileResponse",
    "UserQuotaResponse",
    "UserQuotaUpdate",
    "UserCreditsResponse",
    "UserCreditsAdjust",
    "UserUsageResponse",
    # Meeting
    "AttendeeBase",
    "AttendeeResponse",
    "MeetingBase",
    "MeetingCreate",
    "MeetingUpdate",
    "MeetingListItem",
    "MeetingResponse",
    "MeetingStatusResponse",
    "MeetingResultResponse",
    "AudioUploadResponse",
    "TranscriptUploadResponse",
    "ProcessingStartResponse",
    "ReviewContentResponse",
    "ReviewRequest",
    "ReviewResponse",
    "EmailDraftResponse",
    "EmailReviewRequest",
    "EmailSendResponse",
    # Task
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    # Admin
    "AdminStatsResponse",
    "AdminUserListItem",
    "AdminUserDetail",
    "AdminUserUpdate",
    "AdminMeetingListItem",
    "AdminMeetingStatusResponse",
]