"""current application schema baseline

Revision ID: 20260824_0001
Revises:
Create Date: 2026-08-24 14:28:16.465418
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260824_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('input_token_price', sa.Integer(), nullable=True),
    sa.Column('output_token_price', sa.Integer(), nullable=True),
    sa.Column('audio_minute_price', sa.Integer(), nullable=True),
    sa.Column('flat_fee', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model', 'service_type', name='uq_pricing_provider_model_service')
    )
    op.create_index(op.f('ix_pricing_rules_model'), 'pricing_rules', ['model'], unique=False)
    op.create_index(op.f('ix_pricing_rules_provider'), 'pricing_rules', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_time', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('agenda', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.Text(), nullable=True),
    sa.Column('transcript_file_path', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('raw_transcription', sa.Text(), nullable=True),
    sa.Column('cleaned_transcription', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('redacted_transcription', sa.Text(), nullable=True),
    sa.Column('redacted_summary', sa.Text(), nullable=True),
    sa.Column('redacted_decisions', sa.JSON(), nullable=False),
    sa.Column('redacted_action_items', sa.JSON(), nullable=False),
    sa.Column('email_draft', sa.Text(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_response', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('credits_charged', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UPLOADED', 'QUEUED', 'PROCESSING', 'AWAITING_REVIEW', 'REVISION_REQUESTED', 'AWAITING_EMAIL_REVIEW', 'COMPLETED', 'REJECTED', 'FAILED', 'CANCELLED', name='meetingstatus', native_enum=False), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meetings_project', 'meetings', ['project_name'], unique=False)
    op.create_index('idx_meetings_thread_id', 'meetings', ['thread_id'], unique=False)
    op.create_index('idx_meetings_user_date', 'meetings', ['user_id', 'meeting_date'], unique=False)
    op.create_index('idx_meetings_user_status', 'meetings', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_thread_id'), 'meetings', ['thread_id'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=20), nullable=True),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_credential_user_provider')
    )
    op.create_index(op.f('ix_user_credentials_provider'), 'user_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=False)
    op.create_table('user_credits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_product_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('ai_temperature', sa.Float(), nullable=False),
    sa.Column('ai_max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('response_language', sa.String(length=50), nullable=False),
    sa.Column('transcription_language', sa.String(length=20), nullable=False),
    sa.Column('default_meeting_type', sa.String(length=50), nullable=False),
    sa.Column('generate_summary', sa.Boolean(), nullable=False),
    sa.Column('generate_action_items', sa.Boolean(), nullable=False),
    sa.Column('generate_decisions', sa.Boolean(), nullable=False),
    sa.Column('generate_insights', sa.Boolean(), nullable=False),
    sa.Column('generate_follow_up_email', sa.Boolean(), nullable=False),
    sa.Column('require_human_review', sa.Boolean(), nullable=False),
    sa.Column('require_email_approval', sa.Boolean(), nullable=False),
    sa.Column('redact_sensitive_information', sa.Boolean(), nullable=False),
    sa.Column('summary_style', sa.String(length=30), nullable=False),
    sa.Column('summary_sections', sa.JSON(), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('notify_processing_finished', sa.Boolean(), nullable=False),
    sa.Column('notify_processing_failed', sa.Boolean(), nullable=False),
    sa.Column('notify_review_required', sa.Boolean(), nullable=False),
    sa.Column('notify_email_approval_required', sa.Boolean(), nullable=False),
    sa.Column('notify_credits_low', sa.Boolean(), nullable=False),
    sa.Column('recording_retention', sa.String(length=20), nullable=False),
    sa.Column('keep_transcript', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_quotas',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_meeting_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('meetings_processed', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_user_usage_user_month')
    )
    op.create_index('idx_user_usage_user_month_desc', 'user_usage', ['user_id', 'month'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_user_usage_month'), 'user_usage', ['month'], unique=False)
    op.create_index(op.f('ix_user_usage_user_id'), 'user_usage', ['user_id'], unique=False)
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendees_meeting', 'attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_attendees_meeting_id'), 'attendees', ['meeting_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('usage_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=True),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_meeting_id'), 'credit_transactions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('meeting_ai_overrides',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_usage_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=True),
    sa.Column('llm_provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('transcription_usage_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=True),
    sa.Column('transcription_provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=True),
    sa.Column('transcription_model', sa.String(length=100), nullable=True),
    sa.Column('email_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=True),
    sa.Column('email_provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_index(op.f('ix_meeting_ai_overrides_user_id'), 'meeting_ai_overrides', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('meeting_title', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority', native_enum=False), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('action_item_index', sa.Integer(), nullable=False),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assignee', 'tasks', ['assignee'], unique=False)
    op.create_index('idx_tasks_meeting', 'tasks', ['meeting_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_meeting_id'), 'tasks', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('usage_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('credits_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_meeting_id'), 'usage_records', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('user_ai_config',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_usage_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=False),
    sa.Column('llm_provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_credential_id', sa.Integer(), nullable=True),
    sa.Column('transcription_usage_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=False),
    sa.Column('transcription_provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=False),
    sa.Column('transcription_model', sa.String(length=100), nullable=True),
    sa.Column('transcription_credential_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_credential_id'], ['user_credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcription_credential_id'], ['user_credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_email_config',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_mode', sa.Enum('APP_CREDITS', 'BYOK', name='aiusagemode'), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'GROQ', 'ANTHROPIC', 'GEMINI', 'OPENROUTER', 'RESEND', 'MAILGUN', 'SMTP', name='providertype'), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['user_credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError(
        "The current-schema baseline cannot be downgraded safely because that "
        "would delete all application tables and data. Restore from a verified "
        "backup instead."
    )
