"""Database module for Meeting Notes API."""
from meeting_notes_agent.database.models import (
    Base,
    User,
    UserRole,
    UserQuota,
    UserCredits,
    UserUsage,
    Meeting,
    Attendee,
    Task,
    TaskStatus,
    TaskPriority,
    MeetingStatus,
)
from meeting_notes_agent.database.models_ai_config import (
    ProviderType,
    AIUsageMode,
    UserAIConfig,
    UserCredential,
    UserEmailConfig,
    CreditTransaction,
    UsageRecord,
    MeetingAIOverride,
    PricingRule,
)
from meeting_notes_agent.database.session import engine, SessionLocal, get_db, init_db, close_db
from meeting_notes_agent.database.repositories import (
    UserRepository,
    UserQuotaRepository,
    UserCreditsRepository,
    UserUsageRepository,
    MeetingRepository,
    AttendeeRepository,
    TaskRepository,
)

__all__ = [
    "Base",
    "User",
    "UserRole",
    "UserQuota",
    "UserCredits",
    "UserUsage",
    "Meeting",
    "Attendee",
    "Task",
    "TaskStatus",
    "TaskPriority",
    "MeetingStatus",
    "ProviderType",
    "AIUsageMode",
    "UserAIConfig",
    "UserCredential",
    "UserEmailConfig",
    "CreditTransaction",
    "UsageRecord",
    "MeetingAIOverride",
    "PricingRule",
    "engine",
    "SessionLocal",
    "get_db",
    "init_db",
    "close_db",
    "UserRepository",
    "UserQuotaRepository",
    "UserCreditsRepository",
    "UserUsageRepository",
    "MeetingRepository",
    "AttendeeRepository",
    "TaskRepository",
]